### ISSUE TITLE
No readme found on the repo

### ISSUE THREAD

**Issue by the1Riddle** [blvck-root/alx_plato#1]
<h2>Hello</h2>

just came across the repo but unfortunately, there is no readme to illustrate the usage.

<h3> What will having a readme help the community with?</h3>

- [x] It will provide more info on how to use it.
- [x] Provide us with the tools needed to run the project.

***thanks***

**Comment by mtndlovu** [comment]
Thank you for raising this issue. I have updated the README.

**Comment by the1Riddle** [comment]
awesome, Hoo haaa! 💪💪
